### ISSUE TITLE
default.html

### ISSUE THREAD

**Issue by nathanieloffer** [dashingcode/front-cover#4]
It appears the theme is missing the _layouts/default.html file that is required for it to build. 

Would it be possible to add this to the repository?

**Comment by dashingcode** [comment]
Hi @nathanieloffer 

I don't have the newest jekyll release on my linux distro. I guess the maintainers are a little late on updating their packages. 

Anyways I don't have this problem on my version (v2.2.0). I can add an empty default.html easily of course if that fixes the problem.

Can you please tell me what jekyll version you are running?

Best regards

Oh and sorry for my late reply. My life has been quite hectic the last couple of weeks...

**Comment by nathanieloffer** [comment]
That's fine I managed to work it out without needing that file. Thanks for following up on it though
